name: Deploy master

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Run tests using dev Dockerfile (this is fine)
      - name: Run tests
        run: |
          docker build -t react-test -f Dockerfile.dev .
          docker run -e CI=true react-test npm test

      # Create deployment zip (cleaned)
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' 'node_modules/*'

      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Frontend
          environment_name: Frontend-Env
          existing_bucket_name: elasticbeanstalk-ap-south-1-881605784981
          version_label: ${{ github.sha }}
          region: ap-south-1
          deployment_package: deploy.zip